//
// Created by wangxn on 2018/5/22.
//

#ifndef DATA_STRUCTURE_C_TESTDYNAMICPROGRAMMING_H
#define DATA_STRUCTURE_C_TESTDYNAMICPROGRAMMING_H


void testDynamicProgramming();

#endif //DATA_STRUCTURE_C_TESTDYNAMICPROGRAMMING_H
